#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e
cd "$(dirname $0)"/..

# Expose a utility library to each of the installer scripts
export DOTFILES_ROOT=$(pwd -P)
export DOTFILES_LIB="${BASH_SOURCE%/*}/lib"

# echo "› brew bundle"
# brew bundle

# Find the installers and run them iteratively
find . -name install.sh | while read installer ; do 
  sh -c "${installer}" ;
done

export -n DOTFILES_ROOT
export -n DOTFILES_LIB

